# fly.toml app configuration file generated for my-profile-4qitjq on 2025-09-02T08:01:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-profile-4qitjq'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
