app = "my-profile-6aehfg"
primary_region = "gru"

[build]

[env]
  VITE_API_BASE_URL = "https://devprofile-api-z0w7.onrender.com/api/v1"
  VITE_APP_NAME = "My Profile"
  VITE_APP_VERSION = "1.0.0"
  VITE_NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  timeout = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
